os: linux
language: android
env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: AKEaJM+7fk/AyTCjuB2jhrEO2rowGwL860L7Qg26rUmrehhoskxaWj+KlJs8PVQ232Tn7mp7Uja4upzxayjUGwbh2lvkYfiEfBD1gjI+GBxHtV3iVu9i5drU4WTy/9xId1zVa5IdLwKe/geHkmrNtkf/KFV6ZMysvAFT5Na4AAceejiK6R/lEFqDQFP6Wo6gfRjb8PftAyHz0VSxkGc8RRNhhqAEMk2R0edI9rc2mbEJ0RFLZkfQwENmhsn0uW2SXeKQiGH8G8hM3AaL4JaXjkdE3H6U1I3Wkh4FlF+sNj7c8bhFHy/swl3nXTthnecwxkBfEH0CHQS5MYiNK0OcjeEGj1cShjDob1VJEjiISQCnjqIZHCFcC/xcjVJGFBSFJN3RmfmfF1w+f0VXjTG0lSdspNbLnwXl0h1NACRAoNPstanFp8riQtjsT175Kf+/s2JwwMZ38XqD3I4FSu0cQMk/2zvEL9SYJK6eNduW+3qg4cOhNLI3cVO5KSHuDylsZokmkZT6yrM0+mLWK+BW7oOPhkY+5hLDJvmVHa3UcCesyqEMvdgXWX8frwk7B3Na7nd5e37l6716Lg3Z2bbmdJ2F+VlgkHD/t8ZpjDxPeyE0WB82SojrRtZBDfhDY+0uwSMZgdAWsA7Zf40hgSNfTQ8NKZfKQTwn1vrg3C7sdcU=
  - secure: n5K9DT8HoRGzEJ63M2q47D8fT0br1hAj5sQNCiFX/vRIXFDY7YFt1nKT/liJOCYMA8Cf+MXj4UhEWRQfWtn0GNu6J7XiHscCmVyecadiaUwkloVMz0wwHsufRiWz8jDAGTYEv5wV2Zosx28cHQHlwj/7Ojd099PcqFEf1QcC1SikjVMtyO+CsW1QDB5kHzu6O6MKyJSQcTI/HqFPateXOczEvQn+2zh6UnhrBx+Wrsxx1TSiYuB258FMl7tNjR+weoqE/ihMYy846Py4agi1G0dZzYII3WOyqNLIkOgFfJGVz3QLcvNJ6TG1xn9krR/lmh78DxdsH2v2Hu/wKdzSakdC8Tw1IGEd1PsKfS82JRJL7Kgiv1Fjawf0ach58f/X019tpt1nIrrqtU9tXukSzFyzVMY0GiywMAkLmQQ5HtPPWy6NxoAW7Hdrb7biSV+m9oO+48T+T2q/Z2du79JFEeXAUeo8tUsSaGIucclaSQd/2cF31O/PunsSSP4BDEBNx009qMwBpTBvt9UxQl7FrldX8BSA2PrbO7jYC80lGCgjeQGqJkWbcGW3BvYXgzrxhQiJ3n51wx5oCZtuSW5g8xPnuyl8LGGkttwZB+Pq7gSW8A3dTwqEkIfMLJ7w+DIbqykbgjh87UBVc2TPOpqczeGiho5zJuNCgv68guIo8Fo=
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - sys-img-armeabi-v7a-google_apis-25
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-android-support
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
jdk: oraclejdk8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
before_install:
- openssl aes-256-cbc -K $encrypted_96f893f84eae_key -iv $encrypted_96f893f84eae_iv
  -in android/secrets.tar.enc -out android/secrets.tar -d
- tar xvf android/secrets.tar -C android/
- yes | sdkmanager --update
- yes | sdkmanager --licenses >/dev/null
- cd $TRAVIS_BUILD_DIR
- wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh
  -O pgyer_upload.sh
- chmod +x pgyer_upload.sh
before_script:
- git clone https://github.com/flutter/flutter.git -b beta --depth 1
script:
- "./flutter/bin/flutter upgrade"
- "./flutter/bin/flutter -v build apk --release"
after_script:
  - set -e
  - $TRAVIS_BUILD_DIR/pgyer_upload.sh "${TRAVIS_BUILD_DIR}/build/app/outputs/apk/release/app-release.apk"
    "1357e2c0fa0304a2c2753ee25cdd511a"
  - rm $TRAVIS_BUILD_DIR/pgyer_upload.sh
#deploy:
#  provider: releases
#  api_key:
#    secure: B7gU0fBZVZxNm7pe7tIkyZbdQd2HqOJfRibDXY4O7gB1veM4NIcTgxmbdim4RkJtUh2DKTswt5G62pnRR7cMLzsFxp22YBcgaacLkUXqUQUPrAoc5fdfjK5FFFhQr00TBG3Moyd6pFEB8YzNAgawK5wCWVlIayyh3VBY+I+ZdZ7SGPDQXjgXoy/1hrVFrHangfhQuXHBN12/Z+IQyMWdKXB2HK9FqgAcL21K/T4/xqYCgMuf0/tOgMxcy2qwOcuTczd8mVmNswbqAyc6cc9d0E5k9LzDb193zfuMUZFwQb2pmm0xBo5C79Ygfd9p1jzdXkRStTzyMVRbZgWuBwL4u8iBt8BiW8X8tiSxz8XwxawapQtIqC9lu02YsSUXyv8XZjUFkjfXJlf4vnFmteu3xeRjoy9CWbgMrfbEfUaxuTI5HGuUyqM7FFeYEHyUqvaNyYZ49abyyu7Rr6JzXkD6c6qDMyM/tiYElHvFgiaI6PWKn/7EZjb/rlH4L+I0zGPepdibtxigwy9cqtIOwTT3Dgcz7w9z2vDnH9DjF7APXFLWA5TBw+ZGmS+lAvDm97/MRhdYNV5Su2X7jTfk8X/kH8MPHq6KwV9wcGoQaUy+7CSOEOtn8AGUXiXbZYwnls0EzhHsquX6uL1znrZNkQWs0x3xmsOdFCWvHIlLo2nTLUQ=
#  file: build/app/outputs/apk/release/app-release.apk
#  on:
#    repo: dsmjoy/codemagic_test
